server:
  port: 9091

spring:
  application:
    name: "account"
  profiles:
    active: prod
  config:
    import: "optional:configserver:http://localhost:9071"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  enpoint:
    shutdown:
      access: unrestricted

endpoints:
  shutdown:
    enabled: true

  info:
    env:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

  instance:
    prefer-ip-address: true



info:
  app:
    name: "Account"
    description: "Mico Bank account application"
    version: "1.0.0"





















# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    deep-linking: true
    show-common-extensions: true
  show-actuator: false
  use-fqn: true
