server:
  port: 9091

spring:
  application:
    name: "account"
  profiles:
    active: prod
  config:
    import: "optional:configserver:http://localhost:9071"


























# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    deep-linking: true
    show-common-extensions: true
  show-actuator: false
  use-fqn: true
